print("AND")
print(f"True + True = {True and True}")
print(f"True + False = {True and False}")
print(f"False + True = {False and True}")
print(f"False + False = {False and False}")
print(f"OR")
print(f"True + True = {True or True}")
print(f"True + False = {True or False}")
print(f"False + True = {False or True}")
print(f"False + False = {False or False}")
