// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Practicum_5;

#nullable disable

namespace Practicum_5.Migrations
{
    [DbContext(typeof(CompanyContext))]
    partial class CompanyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Practicum_5.Department", b =>
                {
                    b.Property<int>("Dnumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Dnumber"));

                    b.Property<string>("Dname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mgr_ssn")
                        .HasColumnType("varchar(9)");

                    b.Property<DateOnly?>("Mgr_start_date")
                        .HasColumnType("date");

                    b.HasKey("Dnumber");

                    b.HasIndex("Mgr_ssn")
                        .IsUnique();

                    b.ToTable("departments");
                });

            modelBuilder.Entity("Practicum_5.Dependent", b =>
                {
                    b.Property<string>("Essn")
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Dependent_name")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Bdate")
                        .HasColumnType("date");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("Sex")
                        .HasColumnType("character(1)");

                    b.HasKey("Essn", "Dependent_name");

                    b.ToTable("dependents");
                });

            modelBuilder.Entity("Practicum_5.Dept_Location", b =>
                {
                    b.Property<int>("Dno")
                        .HasColumnType("integer");

                    b.Property<string>("Dlocation")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Dno", "Dlocation");

                    b.ToTable("dept_Locations");
                });

            modelBuilder.Entity("Practicum_5.Employee", b =>
                {
                    b.Property<string>("SSN")
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Bdate")
                        .HasColumnType("date");

                    b.Property<int?>("DNo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<char?>("Sex")
                        .HasColumnType("character(1)");

                    b.Property<string>("Super_ssn")
                        .HasColumnType("varchar(9)");

                    b.Property<string>("fName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SSN");

                    b.HasIndex("DNo");

                    b.HasIndex("Super_ssn");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Practicum_5.Project", b =>
                {
                    b.Property<int>("Pnumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Pnumber"));

                    b.Property<int?>("DNo")
                        .HasColumnType("integer");

                    b.Property<string>("Plocation")
                        .HasColumnType("text");

                    b.Property<string>("Pname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Pnumber");

                    b.HasIndex("DNo");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("Practicum_5.WorksOn", b =>
                {
                    b.Property<int>("Pno")
                        .HasColumnType("integer");

                    b.Property<string>("Essn")
                        .HasColumnType("varchar(9)");

                    b.Property<int>("Hours")
                        .HasColumnType("integer");

                    b.HasKey("Pno", "Essn");

                    b.HasIndex("Essn");

                    b.ToTable("worksOn");
                });

            modelBuilder.Entity("Practicum_5.Department", b =>
                {
                    b.HasOne("Practicum_5.Employee", "Manager")
                        .WithOne()
                        .HasForeignKey("Practicum_5.Department", "Mgr_ssn");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Practicum_5.Dependent", b =>
                {
                    b.HasOne("Practicum_5.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("Essn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Practicum_5.Dept_Location", b =>
                {
                    b.HasOne("Practicum_5.Department", "Dept")
                        .WithMany()
                        .HasForeignKey("Dno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("Practicum_5.Employee", b =>
                {
                    b.HasOne("Practicum_5.Department", "Department")
                        .WithMany("EmpInDept")
                        .HasForeignKey("DNo");

                    b.HasOne("Practicum_5.Employee", "Supervisor")
                        .WithMany()
                        .HasForeignKey("Super_ssn");

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Practicum_5.Project", b =>
                {
                    b.HasOne("Practicum_5.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("DNo");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Practicum_5.WorksOn", b =>
                {
                    b.HasOne("Practicum_5.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Essn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practicum_5.Project", "Project")
                        .WithMany()
                        .HasForeignKey("Pno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Practicum_5.Department", b =>
                {
                    b.Navigation("EmpInDept");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Practicum_5.Employee", b =>
                {
                    b.Navigation("Dependents");
                });
#pragma warning restore 612, 618
        }
    }
}
